### ISSUE TITLE
NetworkChunk#setContainer causes the server to crash

### ISSUE THREAD

**Issue by yaroslav4167** [Yeregorix/AntiXray#1] opened 2018-05-01 20:48 UTC
Server: SpongeForge-1.12.2-2655-7.1.0-BETA-3064
CrashLog-1: https://pastebin.com/irAj42vh
CrashLog-2: https://pastebin.com/7zcHC3Gj

A certain portion of the world, causes this error.

**Comment by treyzania** [comment] 2018-05-15 00:42
Also was getting this issue, and it also seems like the plugin was sometimes failing to actually hide ores like expected.

```
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-06016f29
SpongeVanilla: 1.12.2-7.1.0-BETA-33
```

**Comment by Yeregorix** [comment] 2018-05-20 08:43
@treyzania I did a fix in latest commit but I'm still unable to reproduce this issue on my computer. Can you compile from `master` and tell me whether this issue is fixed ?

**Comment by yaroslav4167** [comment] 2018-05-20 09:28
I re-created the map and did not see this problem again.

**Comment by treyzania** [comment] 2018-05-20 20:59
I've been running the server for a few hours now and it *appears* to be fixed, I'll let you know if it continues.

**Comment by Yeregorix** [comment] 2018-05-26 13:54
Does this issue has reappeared during these last days ?

**Comment by Yeregorix** [comment] 2018-05-26 19:35
I'm closing this issue but feel free to reopen if the issue reappear.

**Closed by Yeregorix** 2018-05-26 19:35 UTC
