### ISSUE TITLE
Console-Spam when loading world

### ISSUE THREAD

**Issue by yaroslav4167** [Yeregorix/AntiXray#6] opened 2018-05-27 12:20 UTC
Hi. I found another minor mistake.
DIM144 - CompactMachines world.
Plugin Version: 1.3.0
```
[14:14:20] [Server thread/INFO] [AntiXray]: Loading configuration for world DIM144 ..
[14:14:43] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Place$Impl to Plugin{id=antixray, name=AntiXray, version=1.3.0, description=A powerful solution against xray users, authors=[Yeregorix], source=./mods/(P)AntiXray-1.3.0.jar}
java.lang.IllegalStateException: Chunk must be fully obfuscated
        at net.smoofyuniverse.antixray.impl.network.NetworkWorld.reobfuscateArea(NetworkWorld.java:453) ~[NetworkWorld.class:?]
        at net.smoofyuniverse.antixray.api.volume.BlockView.reobfuscateSurrounding(BlockView.java:231) ~[BlockView.class:?]
        at net.smoofyuniverse.antixray.api.volume.WorldView.reobfuscateSurrounding(WorldView.java:170) ~[WorldView.class:?]
        at net.smoofyuniverse.antixray.api.volume.WorldView.reobfuscateSurrounding(WorldView.java:157) ~[WorldView.class:?]
        at net.smoofyuniverse.antixray.event.WorldEventListener.reobfuscateSurrounding(WorldEventListener.java:107) ~[WorldEventListener.class:?]
        at net.smoofyuniverse.antixray.event.WorldEventListener.lambda$onBlockChange$0(WorldEventListener.java:74) ~[WorldEventListener.class:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_151]
        at net.smoofyuniverse.antixray.event.WorldEventListener.onBlockChange(WorldEventListener.java:74) ~[WorldEventListener.class:?]
        at org.spongepowered.common.event.listener.ChangeBlockEventListener_WorldEventListener_onBlockChange74.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2703-7.1.0-BETA-3116]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:381) ~[SpongeModEventManager.class:1.12.2-2703-7.1.0-BETA-3116]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:358) ~[SpongeModEventManager.class:1.12.2-2703-7.1.0-BETA-3116]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:415) ~[SpongeModEventManager.class:1.12.2-2703-7.1.0-BETA-3116]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:403) ~[SpongeModEventManager.class:1.12.2-2703-7.1.0-BETA-3116]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:442) ~[SpongeEventManager.class:1.12.2-2703-7.1.0-BETA-3116]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) ~[SpongeImpl.class:1.12.2-2703-7.1.0-BETA-3116]
        at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:605) ~[TrackingUtil.class:1.12.2-2703-7.1.0-BETA-3116]
        at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:524) ~[TrackingUtil.class:1.12.2-2703-7.1.0-BETA-3116]
        at org.spongepowered.common.event.tracking.phase.plugin.PreWorldTickListenerState.lambda$unwind$0(PreWorldTickListenerState.java:51) ~[PreWorldTickListenerState.class:1.12.2-2703-7.1.0-BETA-3116]
        at org.spongepowered.common.event.tracking.context.CapturedSupplier.acceptAndClearIfNotEmpty(CapturedSupplier.java:69) [CapturedSupplier.class:1.12.2-2703-7.1.0-BETA-3116]
        at org.spongepowered.common.event.tracking.phase.plugin.PreWorldTickListenerState.unwind(PreWorldTickListenerState.java:50) [PreWorldTickListenerState.class:1.12.2-2703-7.1.0-BETA-3116]
        at org.spongepowered.common.event.tracking.phase.plugin.PreWorldTickListenerState.unwind(PreWorldTickListenerState.java:39) [PreWorldTickListenerState.class:1.12.2-2703-7.1.0-BETA-3116]
        at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:213) [PhaseTracker.class:1.12.2-2703-7.1.0-BETA-3116]
        at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:439) [PhaseContext.class:1.12.2-2703-7.1.0-BETA-3116]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:653) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:286) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[14:14:50] [Server thread/INFO] [Sponge]: Unloading world [DIM144] (DIM144)

```

**Comment by Yeregorix** [comment] 2018-05-27 13:42
Duplicate of #5
It should have been fixed in the latest commit (≈ 4 hours ago).
Did you compiled before or after this commit?

**Comment by yaroslav4167** [comment] 2018-05-27 15:08
Oh.. No i'm used yesterday's version.

**Comment by Yeregorix** [comment] 2018-05-27 15:53
No problem ^^

**Closed by Yeregorix** 2018-05-27 15:53 UTC
