### ISSUE TITLE
Exception when placing blocks: "Chunks must be fully obfuscated"

### ISSUE THREAD

**Issue by treyzania** [Yeregorix/AntiXray#5] opened 2018-05-26 22:46 UTC
Looks like a multithreading issue, probably need more `synchronized` blocks.  This was on `b82557a`.

```
[22:43:21 ERROR] [Sponge]: Could not pass ChangeBlockEvent$Place$Impl to Plugin{id=antixray, name=AntiXray, version=1.3.0, description=A powerful solution against xray users, authors=[Yeregorix], source=mods/AntiXray-b82557a.jar}
java.lang.IllegalStateException: Chunks must be fully obfuscated
        at net.smoofyuniverse.antixray.impl.network.NetworkWorld.reobfuscateArea(NetworkWorld.java:465) ~[NetworkWorld.class:?]
        at net.smoofyuniverse.antixray.api.volume.BlockView.reobfuscateSurrounding(BlockView.java:231) ~[BlockView.class:?]
        at net.smoofyuniverse.antixray.api.volume.WorldView.reobfuscateSurrounding(WorldView.java:170) ~[WorldView.class:?]
        at net.smoofyuniverse.antixray.api.volume.WorldView.reobfuscateSurrounding(WorldView.java:157) ~[WorldView.class:?]
        at net.smoofyuniverse.antixray.event.WorldEventListener.reobfuscateSurrounding(WorldEventListener.java:107) ~[WorldEventListener.class:?]
        at net.smoofyuniverse.antixray.event.WorldEventListener.lambda$onBlockChange$0(WorldEventListener.java:74) ~[WorldEventListener.class:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_171]
        at net.smoofyuniverse.antixray.event.WorldEventListener.onBlockChange(WorldEventListener.java:74) ~[WorldEventListener.class:?]
        at org.spongepowered.common.event.listener.ChangeBlockEventListener_WorldEventListener_onBlockChange68.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.0-BETA-53]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:419) ~[SpongeEventManager.class:1.12.2-7.1.0-BETA-53]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:455) ~[SpongeEventManager.class:1.12.2-7.1.0-BETA-53]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:442) ~[SpongeEventManager.class:1.12.2-7.1.0-BETA-53]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:217) ~[SpongeImpl.class:1.12.2-7.1.0-BETA-53]
        at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:605) ~[TrackingUtil.class:1.12.2-7.1.0-BETA-53]
        at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:524) ~[TrackingUtil.class:1.12.2-7.1.0-BETA-53]
        at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.lambda$unwind$0(BlockTickPhaseState.java:84) ~[BlockTickPhaseState.class:1.12.2-7.1.0-BETA-53]
        at org.spongepowered.common.event.tracking.context.CapturedSupplier.acceptAndClearIfNotEmpty(CapturedSupplier.java:69) [CapturedSupplier.class:1.12.2-7.1.0-BETA-53]
        at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.unwind(BlockTickPhaseState.java:84) [BlockTickPhaseState.class:1.12.2-7.1.0-BETA-53]
        at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.unwind(BlockTickPhaseState.java:51) [BlockTickPhaseState.class:1.12.2-7.1.0-BETA-53]
        at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:213) [PhaseTracker.class:1.12.2-7.1.0-BETA-53]
        at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:439) [PhaseContext.class:1.12.2-7.1.0-BETA-53]
        at org.spongepowered.common.event.tracking.TrackingUtil.updateTickBlock(TrackingUtil.java:286) [TrackingUtil.class:1.12.2-7.1.0-BETA-53]
        at net.minecraft.world.WorldServer.redirect$onUpdateTick$zli000(SourceFile:2065) [oo.class:?]
        at net.minecraft.world.WorldServer.func_72955_a(SourceFile:641) [oo.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(SourceFile:220) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1616) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

```

This is on the latest version of SpongeVanilla, build 53 for 1.12.2.

**Comment by Yeregorix** [comment] 2018-05-27 08:52
This issue was caused by a block placement. Do you know if this block placement was caused by a player or by anything else ?

**Comment by Yeregorix** [comment] 2018-05-27 09:02
Okey, I just reproduced the issue, this is caused by block changes during post world generation. It will be fixed soon.

**Closed** 2018-05-27 09:37 UTC

**Comment by treyzania** [comment] 2018-05-28 02:51
That's a hilarious commit ID.
