### ISSUE TITLE
Strange behavior if you installed the plugin

### ISSUE THREAD

**Issue by ziceptor** [Yeregorix/AntiXray#4] opened 2018-03-19 19:23 UTC
only world "wf" when you use your right hand

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2970.jar
AntiXray-1.2.4.jar
config default

[fml-junk-earlystartup.log](https://gist.github.com/ziceptor/8fef5cdc769f38968b6b678c908f9e9c)
[fml-server-latest.log](https://gist.github.com/ziceptor/7cf38e65f90f8b18aca9671c2811895c)
[world config](https://gist.github.com/ziceptor/1fc76fed01fc4b3938b05f367fc777d9)

[video](https://www.youtube.com/watch?v=LHltVOu4xbI)

**Comment by Yeregorix** [comment] 2018-03-20 18:36
That's very strange, can you send me the list of your mods and plugins ? In private if you want, or at least a minimal setup to reproduce the error.

**Comment by Tollainmear** [comment] 2018-03-23 12:51
whoops, has the same problem as that with latest antiXray XD
but this only appear in DIM1, no exceptions in console.

**Comment by ziceptor** [comment] 2018-03-23 12:55
- ActionBroadcaster.jar
- ActiveTime-s7.1-v1.4.1.jar
- AntiXray-1.2.4.jar!
- CatClearLag-0.8.2.jar
- ChangeSkinSponge.jar
- ChestRefill-1.12.2-1.2.1.jar
- chopchop.jar
- console-lock-1.1.1.jar
- controlc.jar
- craftbook-sponge-S7.1-4.0-SNAPSHOT-dist.jar
- denizen2core-0.4.0.jar
- denizen2sponge-0.4.0.jar
- DoubleJump-1.5.jar
- DoubleJumpMixins-1.0.jar
- EasyScoreboards.jar
- EconomyLite-7.0.0-2.13.0.jar
- elevator.jar
- extradrop-0.1.2.jar
- FileInventories-0.2.2.jar
- flexiblelogin-0.18.jar
- Gluon-1.0.4.jar
- griefprevention-1.12.2-4.3.0.568.jar
- InstantRespawn.jar
- iplog-0.2.1.jar
- itemduct.jar
- JumpPlates-1.1.jar
- KaroglanSignEditor-3.0.jar
- LangSwitch.jar
- LibCube.jar
- LuckPerms-Sponge-4.1.43.jar
- MagiBridge-API7-2.4.5.1.jar
- MineReset-1.0.8.BETA2.jar
- Nucleus-1.3.4-S7.0-MC1.12.2-plugin.jar
- PlaceholderAPI-4.4.jar
- projectcore-7.1.0-0.2.2.jar
- projectinventories-7.1.0-0.11.2.jar
- projectportals-7.1.0-0.14.3.jar
- RedNestosBoxOUtils-0.3.jar
- SlotMachines-1.4.1.jar
- SmoofyDungeon-1.0.0.jar
- spongeforge-1.12.2-2611-7.1.0-BETA-2970.jar
- TabManager-2.1.0-S7.0-MC1.12.2.jar
- TimTheEnchanter.jar
- TitleMOTD.-.1.0.jar
- VillagerShops.jar
- walletdrop-7.1.0-0.3.0.jar
- worldedit-sponge-6.1.9-SNAPSHOT-dist.jar

Unfortunately, I do not have time to clarify the sequence of actions that led to such behavior.
Maybe later.

**Comment by Yeregorix** [comment] 2018-03-23 20:44
For now I'm unable to reproduce the issue. Is there specific details I should know or steps to reproduce the issue ? 
@Tollainmear Can you send me a list of your mods and plugins as well if possible ? This could help me to detect a conflit if there is one.

**Comment by Tollainmear** [comment] 2018-03-26 05:41
Only three:
- SpongeForge
- nucleus
- anti-Xray

steps:
1. join to server with default config(for each plugin)
2. go to DIM1
3. right click any block with empty hand
4. each block which interacted was disappeared but you can't went through

😅

**Comment by ziceptor** [comment] 2018-03-26 15:05
You could send a test server to the developer.

**Comment by Yeregorix** [comment] 2018-04-11 09:40
This would help me a lot, for now I'm unable to reproduce the issue and it's complicated to fix something we can't reproduce.

**Comment by ziceptor** [comment] 2018-04-11 19:01
I found the backup. Left least plugins. You need the world of wf. https://cloud.mail.ru/public/GPp2/BNFGqNBaw

**Comment by Yeregorix** [comment] 2018-04-11 20:44
Thank you! This should help me a lot. I will do my best to fix the problem!

**Comment by Yeregorix** [comment] 2018-04-12 07:55
The issue should be fixed. Thank you for your help! I will publish the update very soon.

**Closed by Yeregorix** 2018-04-12 07:55 UTC
